-- 코드를 입력하세요
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
from ANIMAL_INS
join ANIMAL_OUTS
on ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
where ANIMAL_INS.SEX_UPON_INTAKE like 'Intact%' and (ANIMAL_OUTS.SEX_UPON_OUTCOME like 'Neutered%' or ANIMAL_OUTS.SEX_UPON_OUTCOME like 'Spayed%')
order by ANIMAL_ID;