# -- 코드를 입력하세요
SELECT USER_ID,NICKNAME,SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER
JOIN USED_GOODS_BOARD
ON USED_GOODS_USER.USER_ID = USED_GOODS_BOARD.WRITER_ID AND STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES>=700000
ORDER BY TOTAL_SALES
